name: google_cloud_storage
version: 0.1.0
description: A sample web application
dependencies:
  collection: '>=0.9.0 <0.10.0'
  google_oauth2_client:
    path: /Users/ovangle/Programming/Dart/dart-google-oauth2-library
  logging: any
  quiver: any
dev_dependencies:
  unittest: any
